- hosts: localhost
  gather_facts: yes
  connection: ssh
  vars:
    identifier: unknown

  tasks:
    - name: Create a kolla network
      sf_network:
        netblock: "10.0.2.0/24"
        name: "kolla"
        namespace: "{{identifier}}"
        state: present
      register: kolla_network

    - debug:
        msg:
          - "Kolla network: {{ kolla_network['meta']['uuid'] }}"

    - name: Create a kolla instance
      sf_instance:
        name: "kolla"
        cpu: 12
        ram: 16384
        disks:
          - "400@rocky:9"
        networkspecs:
          - network_uuid=kolla,address=10.0.2.2,float=true
          - network_uuid=kolla,address=none
        ssh_key: "{{ lookup('file', '/srv/github/id_ci.pub') }}"
        namespace: "{{identifier}}"
        side_channels:
          - sf-agent
        state: present
        await: true
        await_timeout: 600
      register: kolla

    - name: Add kolla node to ansible
      add_host:
        hostname: kolla
        egress_ip: "{{kolla['meta']['interfaces'][0]['ipv4']}}"
        ansible_ssh_host: "{{kolla['meta']['interfaces'][0]['ipv4']}}"
        ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -o GlobalKnownHostsFile=/dev/null -o UserKnownHostsFile=/dev/null"
        ansible_ssh_user: "cloud-user"
        ansible_ssh_private_key_file: "/srv/github/id_ci"
        sf_uuid: "{{kolla['meta']['uuid']}}"
        groups: sfall

    - name: Add kolla network interface to primary instance
      shell: |
        sf-client instance add-interface -n kolla "{{identifier}}"
        sleep 10
        ip a | egrep "^[0-9]+: ens" | cut -f 2 -d " " | sed 's/:.*//'
      register: primary_new_interface

    - debug:
        msg:
          - "New interface on primary: {{ primary_new_interface.stdout }}"

    - name: DHCP on new interface
      become: true
      shell: "dhclient {{ primary_new_interface.stdout }}"

    - name: Collect address details for new interface
      shell: "ip -4 addr show {{ primary_new_interface.stdout }} | grep inet | sed -e 's/.*inet //' -e 's|/.*||'"
      register: primary_new_address

    - name: Log instance details
      debug:
        msg:
          - "Kolla: is {{kolla['meta']['uuid']}} at {{kolla['meta']['interfaces'][0]['ipv4']}}"
          - "Primary kolla network address: {{ primary_new_address.stdout }}"

    - name: Write details of instances to workspace
      copy:
        content: |
          {% for svr in groups.sfall %}
          export {{ svr | replace('-', '_') }}={{hostvars[svr]['ansible_ssh_host']}}
          export {{ svr | replace('-', '_') }}_uuid={{hostvars[svr]['sf_uuid']}}
          {% endfor %}

          export identifier={{identifier}}
          export nodes="{{ groups.sfall | join(' ') | replace('-', '_') }}"
          export KOLLA="{{ primary_new_address.stdout }}"
        dest: "{{ lookup('env', 'GITHUB_WORKSPACE') }}/ci-environment.sh"
        owner: debian
        group: debian
        mode: u=r,g=r,o=r

    - name: Log environment details path
      debug:
        msg: "Environment details written to {{ lookup('env', 'GITHUB_WORKSPACE') }}/ci-environment.sh"

    - name: Wait for all instances to present an "OpenSSH" prompt
      wait_for:
        port: 22
        host: "{{hostvars[item]['ansible_ssh_host']}}"
        search_regex: OpenSSH
        delay: 10
      with_items: "{{ groups['sfall'] }}"