oslo.config-master:
  stage: test
  needs: []
  interruptible: true
  tags:
    - shell
    - vm
  timeout: 120m
  script:
    - ./testapply.sh oslo.config

oslo.config-stable-2023.1:
  stage: test
  needs: []
  interruptible: true
  tags:
    - shell
    - vm
  timeout: 120m
  script:
    - ./testapply.sh oslo.config-2023.1

oslo.config-stable-2023.2:
  stage: test
  needs: []
  interruptible: true
  tags:
    - shell
    - vm
  timeout: 120m
  script:
    - ./testapply.sh oslo.config-2023.2

oslo.config-stable-2024.1:
  stage: test
  needs: []
  interruptible: true
  tags:
    - shell
    - vm
  timeout: 120m
  script:
    - ./testapply.sh oslo.config-2024.1

oslo.config:
  stage: artifacts
  needs:
    - oslo.config-master
    - oslo.config-stable-2023.1
    - oslo.config-stable-2023.2
    - oslo.config-stable-2024.1
  interruptible: true
  tags:
    - shell
    - vm
  artifacts:
    paths:
      - src/oslo.config.tgz
  timeout: 60m
  script:
    - rm -rf src/oslo.config
    - ./testapply.sh --skiptests oslo.config-2023.1
    - ./testapply.sh --skiptests oslo.config-2023.2
    - ./testapply.sh --skiptests oslo.config-2024.1
    - ./testapply.sh --skiptests oslo.config